In [23]:
import kagglehub
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [24]:
#Importando o dataframe que será utilizado

df = pd.read_csv('loan_data.csv')

In [25]:
#Exibindo o dataframe

df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [26]:
#Verificando se existem valores ausentes

df.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [27]:
#Verificando se existem registros duplicados

df.duplicated().sum()

0

In [28]:
#Verificando a quantidade de linhas e colunas

df.shape

(45000, 14)

In [29]:
#Verificando os tipos das colunas

df.dtypes

person_age                        float64
person_gender                      object
person_education                   object
person_income                     float64
person_emp_exp                      int64
person_home_ownership              object
loan_amnt                         float64
loan_intent                        object
loan_int_rate                     float64
loan_percent_income               float64
cb_person_cred_hist_length        float64
credit_score                        int64
previous_loan_defaults_on_file     object
loan_status                         int64
dtype: object

In [30]:
#Verificando o balanceamento da variável target

df['loan_status'].value_counts()

0    35000
1    10000
Name: loan_status, dtype: int64

In [31]:
#Selecionando somente as colunas que serão utilizadas

df = df[['person_age', 'person_education', 'person_income', 'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'credit_score', 'previous_loan_defaults_on_file', 'loan_status']]

In [32]:
#Aplicando LabelEncoder para transformar variáveis categóricas(strings) em valores numéricos

label_encoder = LabelEncoder()
colunas_label_encoder = ['person_education', 'person_home_ownership', 'previous_loan_defaults_on_file']

for col in colunas_label_encoder:
    df[col] = label_encoder.fit_transform(df[col])

In [33]:
#Exibindo o dataframe final

df.head()

,person_age,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_int_rate,loan_percent_income,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,4,71948.0,0,3,35000.0,16.02,0.49,561,0,1
1,21.0,3,12282.0,0,2,1000.0,11.14,0.08,504,1,0
2,25.0,3,12438.0,3,0,5500.0,12.87,0.44,635,0,1
3,23.0,1,79753.0,0,3,35000.0,15.23,0.44,675,0,1
4,24.0,4,66135.0,1,3,35000.0,14.27,0.53,586,0,1

In [34]:
#Criando variável de features

x = df.iloc[:, 0:10].values

In [35]:
#Criando variável de target

y = df.iloc[:, 10].values

In [36]:
#Dividindo os dados em treino(80%) e teste(20%)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [37]:
#Criando arquivo para salvar as variáveis de treino e teste

with open('variaveis_train_test.pkl', mode='wb') as f:
    pickle.dump([x_train, y_train, x_test, y_test], f)

In [38]:
#Criando o modelo Random Forest com 150 árvores, usando entropia como critério de divisão

random_forest = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state=42)

In [39]:
#Treinando o modelo

random_forest.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=42)

In [40]:
#Criando as previsões do modelo

previsoes = random_forest.predict(x_test)

In [41]:
#Exibindo a acuracidade do modelo

accuracy_score(y_test, previsoes)

0.9201111111111111

In [42]:
#Exibindo e analisando as demais métricas do modelo

print(classification_report(y_test, previsoes))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      6990
           1       0.87      0.76      0.81      2010

    accuracy                           0.92      9000
   macro avg       0.90      0.86      0.88      9000
weighted avg       0.92      0.92      0.92      9000

In [43]:
#Exibindo e analisando a matriz de confusão

print(confusion_matrix(y_test, previsoes))

[[6754  236]
 [ 483 1527]]