In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pickle
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

In [3]:
#Importando o dataframe que será utilizado

df = pd.read_csv('card_transdata.csv')

In [4]:
#Exibindo o dataframe

df.head()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0

In [5]:
#Verificando se existem valores ausentes

df.isnull().sum()

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

In [6]:
#Verificando se existem registros duplicados

df.duplicated().sum()

0

In [7]:
#Verificando a quantidade de linhas e colunas

df.shape

(1000000, 8)

In [8]:
#Verificando os tipos das colunas

df.dtypes

distance_from_home                float64
distance_from_last_transaction    float64
ratio_to_median_purchase_price    float64
repeat_retailer                   float64
used_chip                         float64
used_pin_number                   float64
online_order                      float64
fraud                             float64
dtype: object

In [9]:
#Verificando o balanceamento da variável target

df['fraud'].value_counts()

0.0    912597
1.0     87403
Name: fraud, dtype: int64

In [10]:
#Aplicando StandardScaler para padronizar as variáveis numéricas

standard_scaler = StandardScaler()
colunas_standard_scaler = ['distance_from_home', 'distance_from_last_transaction', 'ratio_to_median_purchase_price']

for col in colunas_standard_scaler:
    df[col] = standard_scaler.fit_transform(df[[col]])

In [11]:
#Exibindo o dataframe final

df.head()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,0.477882,-0.182849,0.043491,1.0,1.0,0.0,0.0,0.0
1,-0.241607,-0.188094,-0.189300,1.0,0.0,0.0,0.0,0.0
2,-0.329369,-0.163733,-0.498812,1.0,0.0,0.0,1.0,0.0
3,-0.372854,0.021806,-0.522048,1.0,1.0,0.0,1.0,0.0
4,0.268572,-0.172968,0.142373,1.0,1.0,0.0,1.0,0.0

In [12]:
#Criando variável de features

x = df.iloc[:, 0:7].values

In [13]:
#Criando variável de target

y = df.iloc[:, 7].values

In [14]:
#Dividindo os dados em treino(80%) e teste(20%)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [15]:
#Criando arquivo para salvar as variáveis de treino e teste

with open ('variaveis_train_test.pkl', mode='wb') as f:
    pickle.dump([x_train,y_train,x_test,y_test], f)

In [16]:
#Criando modelo de Regressão Logística. Class_weight='balanced' devido a desbalanceamento de classes.

logistic_regression = LogisticRegression(class_weight='balanced', random_state=42)

In [17]:
#Treinando o modelo

logistic_regression.fit(x_train, y_train)

LogisticRegression(class_weight='balanced', random_state=42)

In [18]:
#Criando as previsões do modelo

previsoes = logistic_regression.predict(x_test)

In [19]:
#Exibindo a acuracidade do modelo

accuracy_score(y_test, previsoes)

0.93472

In [20]:
#Exibindo e analisando as demais métricas do modelo

print(classification_report(y_test, previsoes))

              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96    182557
         1.0       0.58      0.95      0.72     17443

    accuracy                           0.93    200000
   macro avg       0.79      0.94      0.84    200000
weighted avg       0.96      0.93      0.94    200000

In [21]:
#Exibindo e analisando a matriz de confusão

print(confusion_matrix(y_test, previsoes))

[[170349  12208]
 [   848  16595]]