In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pickle
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [10]:
#Importando o dataframe que será utilizado

df = pd.read_excel('bank-full.xlsx')

In [11]:
#Exibindo o dataframe

df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [12]:
#Verificando se existem valores ausentes

df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [13]:
#Verificando se existem registros duplicados

df.duplicated().sum()

0

In [14]:
#Verificando a quantidade de linhas e colunas

df.shape

(45211, 17)

In [15]:
#Verificando os tipos das colunas

df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [16]:
#Verificando o balanceamento da variável target

df['y'].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [17]:
#Removendo colunas que não serão usadas

df.drop(df.columns[[8,9,13]], axis=1, inplace=True)

In [18]:
#Aplicando LabelEncoder para transformar variáveis categóricas(strings) em valores numéricos

label_encoder = LabelEncoder()
colunas_label_encoder = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'month', 'poutcome', 'y']

for col in colunas_label_encoder:
    df[col] = label_encoder.fit_transform(df[col])

In [19]:
#Aplicando StandardScaler para padronizar as variáveis numéricas

standard_scaler = StandardScaler()
colunas_standard_scaler = ['age', 'job', 'marital', 'education', 'balance', 'month', 'duration', 'campaign','previous', 'poutcome']

for col in colunas_standard_scaler:
    df[col] = standard_scaler.fit_transform(df[[col]])

In [20]:
#Exibindo o dataframe final

df.head()

,age,job,marital,education,default,balance,housing,loan,month,duration,campaign,previous,poutcome,y
0,1.606965,-0.103820,-0.275762,1.036362,0,0.256419,1,0,0.823773,0.011016,-0.569351,-0.25194,0.444898,0
1,0.288529,1.424008,1.368372,-0.300556,0,-0.437895,1,0,0.823773,-0.416127,-0.569351,-0.25194,0.444898,0
2,-0.747384,-0.714951,-0.275762,-0.300556,0,-0.446762,1,1,0.823773,-0.707361,-0.569351,-0.25194,0.444898,0
3,0.571051,-1.020516,-0.275762,2.373280,0,0.047205,1,0,0.823773,-0.645231,-0.569351,-0.25194,0.444898,0
4,-0.747384,2.035139,1.368372,2.373280,0,-0.447091,0,0,0.823773,-0.233620,-0.569351,-0.25194,0.444898,0

In [21]:
#Criando variável de features

x = df.iloc[:, 0:13].values

In [22]:
#Criando variável de target

y = df.iloc[:, 13].values

In [23]:
#Dividindo os dados em treino(80%) e teste(20%)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [24]:
#Criando arquivo para salvar as variáveis de treino e teste

with open('variaveis_train_test.pkl', mode='wb') as f:
    pickle.dump([x_train, y_train, x_test, y_test], f)

In [25]:
#Criando modelo SVM com kernel rbf. Ajuste de C=1.0 para controle de margem. Class_weight='balanced' devido a desbalanceamento de classes.

svm = SVC(kernel='rbf', random_state=42, C=1.0, class_weight='balanced')

In [26]:
#Treinando o modelo

svm.fit(x_train, y_train)

SVC(class_weight='balanced', random_state=42)

In [27]:
#Criando as previsões do modelo

previsoes = svm.predict(x_test)

In [28]:
#Exibindo a acuracidade do modelo

print(accuracy_score(y_test, previsoes))

0.8047108260533009

In [29]:
#Exibindo e analisando as demais métricas do modelo

print(classification_report(y_test, previsoes))

              precision    recall  f1-score   support

           0       0.97      0.80      0.88      7952
           1       0.36      0.82      0.50      1091

    accuracy                           0.80      9043
   macro avg       0.67      0.81      0.69      9043
weighted avg       0.90      0.80      0.83      9043

In [30]:
#Exibindo e analisando a matriz de confusão

print(confusion_matrix(y_test, previsoes))

[[6380 1572]
 [ 194  897]]